Add documentation for find_key
jwt/ruby-jwt pull request #426
Opened 2021-06-17 15:43 UTC by ritikesh

NA

2021-06-17 19:17 UTC, anakinj requested changes
Really good addition to visualize how a block can be used to resolve keys.

A test to verify that the example works in the future would be valuable, some are located in [readme_examples_spec.rb](https://github.com/jwt/ruby-jwt/blob/master/spec/integration/readme_examples_spec.rb)

2021-06-17 19:17 UTC, anakinj commented on README.md
> +  decoded_token = JWT.decode(token, nil, true, { iss: iss, verify_iss: true, algorithm: 'HS256' }) do |_headers, payload|
Just a random idea: Would i make sense to have 2 different issuers to pick between in the example.

2021-06-17 19:17 UTC, anakinj commented on README.md
> +To dynamically find the secret that was used for signing the JWT, pass a block to the decode block. The block receives headers and the original payload as parameters. It should return with the secret
To also cover the asymmetric algorithms maybe the wording could be `find the key for verifying the JWT signature`.

The key is not always the secret and not always used for signing tokens.

2021-06-18 10:20 UTC, ritikesh commented
> Really good addition to visualize how a block can be used to resolve keys.
> 
> A test to verify that the example works in the future would be valuable, some are located in [readme_examples_spec.rb](https://github.com/jwt/ruby-jwt/blob/master/spec/integration/readme_examples_spec.rb)

Thanks, I've accommodated the suggestions and added the test case. 👍

2021-06-21 19:57 UTC, anakinj approved these changes

2021-06-22 07:02 UTC, ritikesh commented
Fixed rubocop in https://github.com/jwt/ruby-jwt/commit/8c506e3575e207dd19da25d238dd86481b99d3a3.

2021-06-28 19:19 UTC, merged

2021-06-28 19:19 UTC, anakinj commented
Big thanks for the contribution.