Fix key rotation for EDDSA
jwt/ruby-jwt pull request #491
Opened 2022-06-21 04:08 UTC by n-studio

Fixes #490 

Instead of raising an error when a public key is invalid, we should return `false` so the key finder can test the next key.

2022-06-21 19:23 UTC, anakinj requested changes

2022-06-22 02:50 UTC, n-studio commented
@anakinj Thank you for the review! I updated my code accordingly.

2022-06-22 05:50 UTC, anakinj approved these changes

2022-06-22 05:50 UTC, anakinj commented on spec/jwt_spec.rb
> +            JWT.decode data[alg], wrong_key, true, algorithm: alg
Oh, this was a good catch, the test has been wrong all the time, right. Like passing for the wrong reasons.

2022-06-22 05:55 UTC, anakinj commented
This is great stuff. Thank you for the fix.

2022-06-22 05:55 UTC, merged