Fix traversing not matching header algos
jwt/ruby-jwt pull request #545
Opened 2023-01-27 10:38 UTC by mpospelov

Hello ruby-jwt maintainers! Thank you for these amazing tool. 🙏

Recently in our company we started to thinking of how we could rotate keys with 0 downtime. 

I found that `keyfinder` can actually return array of keys and `ruby-jwt` will iterate through these keys until find a matching one
https://github.com/toptal/ruby-jwt/blob/8963312352f1698091640f3201e930c201ea933e/lib/jwt/decode.rb#L47

**BUT** the problem is that for each key we traverse all allowed algoes in decoder. 
Our provider code supports multiple consumers which encodes payload with different `algo`es, so the current code can lead to the case when we have matching public key returned as second element in keyfinder but we even don't try to decode the payload with it as we fail with attempt to decode with first key but with incorrect algo.

You can find these case in specs and implementation to fix this issue in this PR.

2023-01-29 17:16 UTC, anakinj requested changes

2023-01-29 17:16 UTC, anakinj commented on lib/jwt/decode.rb
> +      @algos = find_valid_algos_in_header
Setting the `@algos` in the middle of everything feels a little wrong.

We are interested in the intersection between the allowed_algorithms and what is specified in the token header, right?

Could there be a method (maybe a memoizing one) that would be used in the `verify_algos` and `verify_signature_for?`?
for example
```
def allowed_and_valid_algorithms
  @allowed_and_valid_algorithms ||= allowed_algorithms.select { |alg| alg.valid_alg?(alg_in_header) }
end
```

2023-01-29 17:19 UTC, anakinj commented
Hi, I think I get the problem and I don't see a problem filtering the list based on the user provided algorithms. I added a comment on the way the algorithms to be used are resolved.

2023-01-30 09:31 UTC, mpospelov commented
Hey @anakinj thank you for your kind review! I addressed rubocop fails and implemented the `#allowed_and_valid_algorithms` as you suggested

2023-01-30 09:59 UTC, mpospelov commented
also `CHANGELOG.md` entry is added 😊

2023-01-30 13:22 UTC, anakinj requested changes

2023-01-30 13:22 UTC, anakinj commented on CHANGELOG.md
Nitpick: Lets keep the placeholder for the next person.
```suggestion
- Your contribution here

```

2023-01-31 05:22 UTC, anakinj approved these changes

2023-01-31 05:24 UTC, merged

2023-01-31 05:24 UTC, anakinj commented
Great improvement. Thank you for the effort.

2023-01-31 11:56 UTC, mpospelov commented
Hey @anakinj! Thank you for all the support and for reviewing my PR 😊 One last thing is don't you mind releasing a new version of `gem`? It would help us a lot 🙏

2023-02-01 21:01 UTC, anakinj commented
New version out. Have fun with it :)