fix signature has expired error if payload is a string
jwt/ruby-jwt pull request #555
Opened 2023-03-04 16:20 UTC by GobinathAL

2023-03-16 19:48 UTC, anakinj reviewed
Im wondering if this is too big of a change for a minor version. This will require the `@payload` to be a Hash or an object responding to `has_key?`. I would also argue that it's totally fine to pass a string as the payload. The RFC states `JWTs encode claims to be transmitted as a JSON [RFC7159] object that is used as the payload of a JSON Web Signature`

2023-07-14 17:33 UTC, GobinathAL commented
> I would also argue that it's totally fine to pass a string as the payload

@anakinj 
If we're allowing String as payload, are we giving users the option to pass expiry time? Either string shouldn't be allowed or i would suggest that it is ok if we don't check for expiry if the payload is string. What are your thoughts?

2023-07-17 19:31 UTC, anakinj commented on lib/jwt/verify.rb
> +      return unless @payload.key?('exp')
What if there would be a method on this class, something like 

```
def contains_key?(payload, key)
  payload.respond_to?(:key?) && payload.key?(key)
end
```

Then this row would be
```
return unless contains_key?(@payload, 'exp')
```

2023-07-17 19:32 UTC, anakinj commented
I think the proposed changes are great but we need to support the case when the passed payload is not responding to the `#key?` method. 

To my understanding passing a string as the payload is not prohibited. What comes to the expiry, [the ´exp´ claim (header) is optional for a JWT token](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.4).

Added a little suggestion on how we could handle such cases.

2023-07-25 19:51 UTC, anakinj approved these changes

2023-07-25 19:52 UTC, anakinj requested changes
Totally forgot to ask if there by any chance would be possible to have some kind of test to validate this change?

2023-07-29 10:37 UTC, anakinj approved these changes

2023-07-29 10:41 UTC, merged

2023-07-29 10:42 UTC, anakinj commented
Great work and thanks for you patience